# Generated by Django 5.2.6 on 2025-09-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
