# Generated by Django 5.2.6 on 2025-09-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanagement', '0002_food_initial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=15),
        ),
    ]
