# Generated by Django 5.2.6 on 2025-09-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanagement', '0006_codsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('takeaway', 'Take Away')], default='delivery', max_length=10),
        ),
    ]
