# Generated by Django 5.2.6 on 2025-09-26 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanagement', '0008_alter_orderdetails_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='food',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodmanagement.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodmanagement.orderdetails')),
            ],
        ),
    ]
